---
# tasks file for layered_packages

- name: Install prescribed set of applications as rpm-ostree layered packages
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: present
    # apply_live: true
  become: yes
  become_method: sudo
  loop:
    - fontconfig
    - gnome-tweaks
    - net-tools
    - python3-psutil
    - vim
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-sound-output-device-chooser
    - gnome-shell-extension-frippery-move-clock
    - gnome-shell-extension-dash-to-dock
    - gnome-shell-extension-gsconnect
    - libratbag-ratbagd
